_target_: gnn.models.MoMLCAModel

backbone:
  _target_: gnn.models.backbones.GINBackbone
  input_dim: 22
  hidden_channels: 128
  num_layers: 4
  dropout: 0.0
  train_eps: false
  pooling: sum

heads: null

optimizer: null
scheduler: null

learning_rate: 0.001
weight_decay: 0.01

property_names:
  - logS
  - logP
  - pKa

task_weights: null

pretrained_backbone:
  checkpoint_path: null
  checkpoint_format: lightning
  backbone_key_prefix: backbone.
  freeze_backbone: false

# compile model for faster training with pytorch 2.0
compile: false
